[WIP] Batch sending of cached qos msg.
nanomq/NanoNNG pull request #1000
Opened 2024-07-02 10:10 UTC by wanghaEMQ

2024-07-11 08:37 UTC, RanMaoyi approved these changes

2024-07-11 08:41 UTC, xinyi-xs approved these changes

2024-07-12 03:45 UTC, JaylinYu requested changes

2024-07-12 03:45 UTC, JaylinYu commented on src/mqtt/protocol/mqtt/mqtt_client.c
> +		while ((packet_id & 0xFFFF) == 0) {
finally someone spot the warning...

2024-07-12 03:45 UTC, JaylinYu commented on src/mqtt/protocol/mqtt/mqtt_client.c
> +			if ((tmsg = nni_aio_get_msg(taio)) != NULL)
possibility to clash with cb of taio. leave msg to the cb(nng_mqtt_client_send_cb)

2024-07-12 03:45 UTC, JaylinYu commented on src/mqtt/protocol/mqtt/mqtt_client.c
> +		nni_msg_clone(msg); // clone for resend, will free when ack received
????

2024-07-12 03:45 UTC, JaylinYu commented on src/mqtt/protocol/mqtt/mqtt_client.c
> +			nni_msg_free(msg);
same here

2024-07-19 02:31 UTC, JaylinYu commented
nothing wrong in this pr now. Just I need more time to test.

2026-08-06 03:27 UTC, closed without merging