Impletment actions related to sqlite config parameters.
nanomq/NanoNNG pull request #167
Opened 2022-06-23 11:30 UTC by alvin1221

1.  set sqlite db PRAGMA;
2. adapt `conf` data structure;
3. db file path can be set by sqlite config file;
4. add column `ts` to tables; 
5. add remove_oldest record APIs;
6. oldest record can be removed by limitation of rows;

2022-06-23 12:50 UTC, JaylinYu approved these changes

2022-06-23 12:56 UTC, JaylinYu requested changes

2022-06-24 02:36 UTC, alvin1221 commented on src/sp/protocol/mqtt/nmq_mqtt.c
> +			nni_qos_db_remove_oldest(is_sqlite,
free msg in `nni_qos_db_set `

2022-06-24 02:38 UTC, alvin1221 commented on src/mqtt/protocol/mqtt/mqtt_client.c
> +		if (s->conf->bridge.sqlite.enable) {
client should use it's own sqlite config;

2022-06-24 07:52 UTC, merged