* NEW [mqtt_parser_test] Add tests for mqtt_parser.c.
nanomq/NanoNNG pull request #411
Opened 2023-01-13 09:48 UTC by Hermann0222

2023-01-13 11:51 UTC, JaylinYu commented
nice try

2023-01-16 03:25 UTC, JaylinYu approved these changes

2023-01-16 03:25 UTC, JaylinYu commented on src/sp/protocol/mqtt/mqtt_parser_test.c
> +	assert(rv == ERR_SUCCESS);
try a opposite test also? input malicious data

2023-01-16 03:26 UTC, JaylinYu commented
CI failed

2023-01-16 03:26 UTC, JaylinYu requested changes
CI failed

2023-01-16 07:51 UTC, Hermann0222 commented
It shoud work now.

2023-01-16 08:40 UTC, Hermann0222 commented on src/sp/protocol/mqtt/mqtt_parser_test.c
> +	assert(rv == ERR_SUCCESS);
ok.

2023-01-16 10:22 UTC, JaylinYu approved these changes
well done

2023-01-16 10:22 UTC, merged