Fix memleak issue of #1050
nanomq/NanoNNG pull request #438
Opened 2023-02-15 04:29 UTC by JaylinYu

related to https://github.com/emqx/nanomq/issues/1043

2023-02-15 04:31 UTC, alvin1221 approved these changes

2023-02-15 07:59 UTC, wanghaEMQ requested changes
Hi. Plz review the comments. There are some critical changes

2023-02-15 07:59 UTC, wanghaEMQ commented on src/sp/protocol/mqtt/mqtt_parser.c
> +		if (rv == 0 && cparam->payload_format_indicator == 0) {
rv has been checked at line 687. The check for rv here is unnecessary

2023-02-15 07:59 UTC, wanghaEMQ commented on src/sp/protocol/mqtt/mqtt_parser.c
> +		} else if (rv == 0 &&
Unnecessary check for rv.

2023-02-15 07:59 UTC, wanghaEMQ commented on src/sp/protocol/mqtt/nmq_mqtt.c
> +		conn_param_clone(cparam);
Clone must before being used!!!

2023-02-15 07:59 UTC, wanghaEMQ commented on src/sp/protocol/mqtt/nmq_mqtt.c
> +		conn_param_clone(cparam);
CLone must before being used!!!

2023-02-15 10:37 UTC, lee-emqx approved these changes

2023-02-16 08:23 UTC, wanghaEMQ approved these changes

2023-02-16 09:48 UTC, merged