Add nni_db_ops structure & APIs
nanomq/NanoNNG pull request #45
Opened 2022-03-23 10:19 UTC by alvin1221

2022-03-24 02:54 UTC, JaylinYu requested changes

2022-03-24 02:54 UTC, JaylinYu commented on src/core/idhash.c
> +	nni_id_map_init(*m, 0, 0, false);
use inline func

2022-03-24 02:58 UTC, alvin1221 commented on src/core/idhash.c
> +	nni_id_map_init(*m, 0, 0, false);
fine...

2022-03-24 12:31 UTC, lee-emqx approved these changes

2022-03-25 07:20 UTC, JaylinYu approved these changes

2022-03-25 07:20 UTC, merged