unit test on nmq-tcp v5 & mqtt_parser & fix memleak in conf free
nanomq/NanoNNG pull request #616
Opened 2023-07-12 09:03 UTC by Hermann0222

2023-07-12 12:22 UTC, RanMaoyi approved these changes

2023-07-13 10:11 UTC, wanghaEMQ approved these changes

2023-07-13 10:21 UTC, RanMaoyi requested changes
sizeof(conf_web_hook_rule *) 
means 
sizeof(struct conf_web_hook_rule *) = 4Byte / 8Byte

2023-07-13 10:57 UTC, lee-emqx approved these changes

2023-07-14 02:57 UTC, Hermann0222 commented on src/sp/protocol/mqtt/mqtt_parser_test.c
> +	extra = pub_extra_alloc(extra);
you are right

2023-07-14 02:57 UTC, Hermann0222 commented on src/sp/protocol/mqtt/mqtt_parser_test.c
> +	NUTS_FAIL(utf8_check((char *) src_0, strlen((char *) src) - 1),
that is my mistake

2023-07-14 03:11 UTC, Hermann0222 commented on src/supplemental/nanolib/conf_test.c
> +	getcwd(cwd,strlen(cwd));
these are debug only, will be commented out soon

2023-07-14 03:11 UTC, Hermann0222 commented on src/supplemental/nanolib/conf_ver2.c
> +		    webhook->rules, cnt * sizeof(conf_web_hook_rule *));
this is how it was designed in the first place in conf.c

2023-07-14 03:21 UTC, RanMaoyi approved these changes
LGTM

2023-07-14 03:21 UTC, RanMaoyi commented on src/supplemental/nanolib/conf_ver2.c
> +		    webhook->rules, cnt * sizeof(conf_web_hook_rule *));
Got it, my fault.

2023-07-14 03:22 UTC, Hermann0222 commented on src/supplemental/nanolib/conf_ver2.c
> +		    webhook->rules, cnt * sizeof(conf_web_hook_rule *));
same as in conf.c gotta to fix that too

2023-07-14 03:26 UTC, RanMaoyi commented on src/supplemental/nanolib/conf_ver2.c
> +		    webhook->rules, cnt * sizeof(conf_web_hook_rule *));
> same as in conf.c gotta to fix that too

webhook->rules is a (void **) type. So it's current to alloc(sizeof(void *)). Do not need to fix that.

2023-07-14 03:34 UTC, merged