tlstran_pipe_stop should free cparam
nanomq/NanoNNG pull request #755
Opened 2023-12-07 02:09 UTC by lkyjason

fixes #1519 Several memleaks in TLS

NanoMQ issue: https://github.com/nanomq/nanomq/issues/1519

p->tcp_cparam that is allocated in tlstran_pipe_nego_cb is not freed by tlstran_pipe_stop, instead the variable is directly set to NULL resulting in memory leak.

2023-12-07 06:31 UTC, OdyWayne commented
Thank you for your contribution! But we usually do frees in pipe_fini not pipe_stop. We will appreciate it if you can move all these to tlstran_pipe_fini, just like what we do in tcptran_pipe_fini. Or should I do it for you?

2023-12-07 06:32 UTC, OdyWayne requested changes
better do this in pipe_fini

2023-12-08 03:00 UTC, JaylinYu approved these changes

2023-12-08 03:00 UTC, JaylinYu commented
Some modification we did on broker_tcp needs to be synced to broker_tls

2023-12-08 03:28 UTC, merged

2023-12-08 03:29 UTC, OdyWayne commented
well done

2023-12-08 15:59 UTC, lkyjason commented
Thank you @OdyWayne