Fix the memory leakage in TLS verifying.
nanomq/NanoNNG pull request #860
Opened 2024-02-17 03:04 UTC by wanghaEMQ

2024-02-17 10:23 UTC, OdyWayne approved these changes

2024-02-18 02:01 UTC, JaylinYu requested changes

2024-02-18 03:40 UTC, wanghaEMQ commented on src/supplemental/quic/msquic_dial.c
> +	if (CredConfig.CertificateFile != NULL)
fixed

2024-02-18 05:26 UTC, JaylinYu approved these changes

2024-02-18 05:26 UTC, merged