Modify cap limit to 0xffffffff for bigger cap support && support cap check.
nanomq/NanoNNG pull request #968
Opened 2024-05-24 10:22 UTC by xinyi-xs

2024-05-26 12:30 UTC, JaylinYu commented
Fix CI then merge

2024-05-26 12:31 UTC, JaylinYu requested changes
just need a little tweaks for small mistak

2024-05-27 06:25 UTC, RanMaoyi approved these changes

2024-05-28 12:08 UTC, JaylinYu approved these changes

2024-05-28 12:08 UTC, merged